### ISSUE TITLE
caldo

### ISSUE THREAD

**Issue by rcastellotti** [fedfontana/mmh-ok#2]
sono qua con i ragazzi e niente e' proprio caldo
ommioddio cosa sto facendo forse dovrei smettere di shitpostare su github se voglio perseguire una carriera accademica
ommioddio perseguire ma come cazzo parlo adesso vado a bermi una tisanina
la noia fa danni gravi

**Comment by rcastellotti** [comment]
(E COMUNQUE A ME I BELINONI AL SUGO PIACCIONO)

**Comment by rcastellotti** [comment]
e niente, [sono anche io un dev dello pensurs](https://github.com/jonhoo/hashbag/pull/17/commits/3e577bf148129674360b10e8a1cd0d4f5b62e3f3)

**Comment by fedfontana** [comment]
Ma Roberto, mi hanno sempre detto che la doc e' importante!!!!! (FOZZA BELINI AL SUGO)

**Comment by rcastellotti** [comment]
BELINI + SUGO TOP RICETTONA

**Comment by fedfontana** [comment]
URCA!
